name: static_compress
version: 0.1.0
description: Compressor (gzip, webp) for static assets.
author: Maxim Dikun <dikmax@gmail.com>
homepage: https://dikmax.name
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: ">=0.13.0 <0.14.0"
  crypto: any
  logging: ">=0.10.0 <0.11.0"
  path: '>=1.0.0 <2.0.0'
  which: ">=0.1.3 <0.2.0"
dev_dependencies:
  unittest: any
